# Generated by Django 4.2 on 2023-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_date_ordered_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='Country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
