# Generated by Django 4.2 on 2023-04-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Country',
            new_name='country',
        ),
    ]
