# Generated by Django 4.2 on 2023-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_shippingaddress_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
